insert into public.portfolio_videos
  (project_key, category_slug, client_slug, client_name, title, description, video_url, thumbnail_url, year, tags, sort_order, featured, published)
values
  ('3d-gadget-animation-p1', 'video-editing', '3d-gadget-animation', '3d Gadget Animation', '3d Gadget Animation — Project 1', '', 'https://vimeo.com/1210032939', '', 2026, '{}', 30, false, true),
  ('3d-gadget-animation-p2', 'video-editing', '3d-gadget-animation', '3d Gadget Animation', '3d Gadget Animation — Project 2', '', 'https://vimeo.com/1210045912', '', 2026, '{}', 31, false, true),
  ('3d-cartoon-animation-p1', '3d-animation', '3d-cartoon-animation', '3d Cartoon Animation', '3d Cartoon Animation — Project 1', '', 'https://vimeo.com/1210037919', '', 2026, '{}', 32, false, true),
  ('3d-cartoon-animation-p2', '3d-animation', '3d-cartoon-animation', '3d Cartoon Animation', '3d Cartoon Animation — Project 2', '', 'https://vimeo.com/1210036662', '', 2026, '{}', 33, false, true),
  ('vape-animation-p1', 'video-editing', 'vape-animation', 'Vape Animation', 'Vape Animation — Project 1', '', 'https://vimeo.com/1210039359', '', 2026, '{}', 34, false, true),
  ('vape-animation-p2', 'video-editing', 'vape-animation', 'Vape Animation', 'Vape Animation — Project 2', '', 'https://vimeo.com/1210041382', '', 2026, '{}', 35, false, true),
  ('3d-explainer-video-p1', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 1', '', 'https://vimeo.com/1210049156', '', 2026, '{}', 36, false, true),
  ('3d-explainer-video-p2', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 2', '', 'https://vimeo.com/1210050482', '', 2026, '{}', 37, false, true),
  ('3d-explainer-video-p3', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 3', '', 'https://vimeo.com/1210052577', '', 2026, '{}', 38, false, true),
  ('3d-explainer-video-p4', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 4', '', 'https://vimeo.com/1210053768', '', 2026, '{}', 39, false, true),
  ('3d-explainer-video-p5', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 5', '', 'https://vimeo.com/1210054201', '', 2026, '{}', 40, false, true),
  ('ronix-p1', 'branding', 'ronix', 'Ronix', 'Ronix — Project 1', '', 'https://vimeo.com/1210047470', '', 2026, '{}', 41, false, true),
  ('mintec-p1', 'branding', 'mintec', 'Mintec', 'Mintec — Project 1', '', 'https://youtu.be/y0tCd75JETE', '', 2026, '{}', 42, false, true),
  ('mintec-p2', 'branding', 'mintec', 'Mintec', 'Mintec — Project 2', '', 'https://youtu.be/DkVe89WP9y4', '', 2026, '{}', 43, false, true),
  ('integra-pw-p1', 'branding', 'integra-pw', 'Integra Pw', 'Integra Pw — Project 1', '', 'https://youtu.be/8OWfEeomZSQ', '', 2026, '{}', 44, false, true),
  ('integra-pw-p2', 'branding', 'integra-pw', 'Integra Pw', 'Integra Pw — Project 2', '', 'https://youtu.be/0SLmd1xJau4', '', 2026, '{}', 45, false, true),
  ('credex-p1', 'branding', 'credex', 'Credex', 'Credex — Project 1', '', 'https://youtu.be/jCvKcYOZN6Y', '', 2026, '{}', 46, false, true),
  ('phr-1-p1', 'branding', 'phr-1', 'Phr 1', 'Phr 1 — Project 1', '', 'https://youtu.be/2T6xaLcR7j0', '', 2026, '{}', 47, false, true),
  ('atx-p1', 'branding', 'atx', 'Atx', 'Atx — Project 1', '', 'https://youtu.be/dieHa2b-aCQ', '', 2026, '{}', 48, false, true),
  ('prov-gap-p1', 'branding', 'prov-gap', 'Prov Gap', 'Prov Gap — Project 1', '', 'https://vimeo.com/1210273972', '', 2026, '{}', 49, false, true),
  ('autoz-crave-p1', 'video-editing', 'autoz-crave', 'Autoz Crave', 'Autoz Crave — Project 1', '', 'https://youtu.be/Au_RJh88iSQ', '', 2026, '{}', 50, false, true),
  ('bag-suitcase-animation-p1', 'video-editing', 'bag-suitcase-animation', 'Bag Suitcase Animation', 'Bag Suitcase Animation — Project 1', '', 'https://youtu.be/cieiw04LGuc', '', 2026, '{}', 51, false, true),
  ('drop-band-animation-p1', 'video-editing', 'drop-band-animation', 'Drop Band Animation', 'Drop Band Animation — Project 1', '', 'https://youtu.be/dfLK-4XvxkQ', '', 2026, '{}', 52, false, true),
  ('drop-band-animation-p2', 'video-editing', 'drop-band-animation', 'Drop Band Animation', 'Drop Band Animation — Project 2', '', 'https://youtu.be/GIex1w7x0-c', '', 2026, '{}', 53, false, true),
  ('3d-medical-animation-p1', '3d-animation', '3d-medical-animation', '3d Medical Animation', '3d Medical Animation — Project 1', '', 'https://youtu.be/_49zfG03G1U', '', 2026, '{}', 54, false, true),
  ('3d-medical-animation-p2', '3d-animation', '3d-medical-animation', '3d Medical Animation', '3d Medical Animation — Project 2', '', 'https://youtu.be/yfGZMp-JKnY', '', 2026, '{}', 55, false, true),
  ('3d-bed-animation-p1', '3d-animation', '3d-bed-animation', '3d Bed Animation', '3d Bed Animation — Project 1', '', 'https://youtu.be/3QJaP9td0Uo', '', 2026, '{}', 56, false, true),
  ('3d-bed-animation-p2', '3d-animation', '3d-bed-animation', '3d Bed Animation', '3d Bed Animation — Project 2', '', 'https://vimeo.com/1210301766', '', 2026, '{}', 57, false, true),
  ('3d-anime-character-p1', '3d-animation', '3d-anime-character', '3d Anime Character', '3d Anime Character — Project 1', '', 'https://youtube.com/shorts/br2ODn6Y6oo', '', 2026, '{}', 58, false, true)
on conflict (project_key) do update set
  category_slug = excluded.category_slug,
  client_slug = excluded.client_slug,
  client_name = excluded.client_name,
  title = excluded.title,
  video_url = excluded.video_url,
  sort_order = excluded.sort_order,
  published = excluded.published;