
insert into public.blog_posts
  (slug, title, excerpt, category, published_at, read_time, image_url, author, sections, featured, published, sort_order)
values
  ('cinematic-trailers-that-convert', 'Why cinematic trailers convert better than product demos', 'Story first launch films build emotional stakes before the CTA. Here is how we structure hooks, pacing, and grade for maximum retention.', 'Strategy', '2026-05-12'::date, '6 min read', '', 'Starlights Visuals', '[{"paragraphs":["Product demos explain features. Cinematic trailers create desire. The difference is narrative architecture how quickly you establish stakes, who the audience is rooting for, and when the payoff lands relative to your call to action.","We see this consistently in paid social and landing page tests: story first launch films hold attention longer, improve thumb stop rates, and lift downstream conversion when the CTA arrives after emotional investment rather than before it."]},{"heading":"Hook structure that holds attention","paragraphs":["The first three seconds should answer one question: why should I care? That can be a visual surprise, a human moment, or a tension the product resolves but it cannot be a logo sting followed by a spec sheet.","We map hooks on a simple grid: problem, escalation, reveal, proof, CTA. Each beat gets a time budget before we ever open a timeline."]}]'::jsonb, true, true, 1),
  ('character-design-for-ip', 'Character design that anchors your IP across every channel', 'From silhouette readability to merch ready turnarounds the checklist we use before a hero goes into production.', 'Craft', '2026-05-03'::date, '5 min read', '', 'Starlights Visuals', '[{"paragraphs":["A strong character is readable at a glance in an app icon, on a billboard, and on a hoodie. Before we animate or rig anything, we pressure test silhouette, expression range, and costume storytelling so the design survives every downstream format."]},{"heading":"Silhouette and expression","paragraphs":["We thumbnail dozens of shapes before color. If you cannot identify the character in pure black fill at 48 pixels, the design is not ready for production.","Expression sheets come early. Campaign characters need to sell joy, frustration, and triumph without dialogue."]}]'::jsonb, true, true, 2),
  ('production-pipelines-that-ship', 'Production pipelines that ship: concept to final delivery', 'How we align art direction, technical constraints, and milestone reviews so teams ship on time without sacrificing polish.', 'Production', '2026-04-21'::date, '8 min read', '', 'Starlights Visuals', '[{"paragraphs":["Projects slip when creative direction and delivery constraints meet for the first time at the end of a milestone. Our pipeline front loads technical limits, establishes a single approval path, and keeps work in progress visible so producers can de risk schedules early."]},{"heading":"Pre production alignment","paragraphs":["We start with a visual target board and a technical brief: resolution, format, lighting model, and animation requirements.","Milestone reviews are structured as gate checks with clear deliverable lists at each stage."]}]'::jsonb, true, true, 3)
on conflict (slug) do update set
  title = excluded.title,
  excerpt = excluded.excerpt,
  category = excluded.category,
  published_at = excluded.published_at,
  read_time = excluded.read_time,
  sections = excluded.sections,
  featured = excluded.featured,
  published = excluded.published,
  sort_order = excluded.sort_order;


insert into public.portfolio_videos
  (project_key, category_slug, client_slug, client_name, title, description, video_url, thumbnail_url, year, tags, sort_order, featured, published)
values
  ('chibi-art-p1', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 1', '', 'https://youtube.com/shorts/cHhg9l3akjU', '', 2026, '{}', 0, false, true),
  ('chibi-art-p2', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 2', '', 'https://youtu.be/iZJPcVn6W9o', '', 2026, '{}', 1, false, true),
  ('chibi-art-p3', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 3', '', 'https://youtu.be/9p4tQexHeoc', '', 2026, '{}', 2, false, true),
  ('vtuber-animation-p1', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 1', '', 'https://vimeo.com/1209255164', '', 2026, '{}', 3, false, true),
  ('vtuber-animation-p2', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 2', '', 'https://vimeo.com/1209258090', '', 2026, '{}', 4, false, true),
  ('vtuber-animation-p3', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 3', '', 'https://youtu.be/O-BoHvEjl7k', '', 2026, '{}', 5, false, true),
  ('vtuber-animation-p4', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 4', '', 'https://vimeo.com/1209843856', '', 2026, '{}', 6, false, true),
  ('vtuber-animation-p5', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 5', '', 'https://youtu.be/e2Doy-zqTOk', '', 2026, '{}', 7, false, true),
  ('vtuber-animation-p6', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 6', '', 'https://vimeo.com/1209847191', '', 2026, '{}', 8, false, true),
  ('vtuber-animation-p7', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 7', '', 'https://youtu.be/qSA1wS9F9Zw', '', 2026, '{}', 9, false, true),
  ('live2d-animation-p1', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 1', '', 'https://youtu.be/4mRu2w4ajGY', '', 2026, '{}', 10, false, true),
  ('live2d-animation-p2', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 2', '', 'https://vimeo.com/1209580152', '', 2026, '{}', 11, false, true),
  ('live2d-animation-p3', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 3', '', 'https://youtu.be/Lz8O7KEBFdQ', '', 2026, '{}', 12, false, true),
  ('live2d-animation-p4', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 4', '', 'https://youtube.com/shorts/EyPeketx70A', '', 2026, '{}', 13, false, true),
  ('live2d-animation-p5', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 5', '', 'https://youtube.com/shorts/tYc1L2uSahI', '', 2026, '{}', 14, false, true),
  ('live2d-animation-p6', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 6', '', 'https://vimeo.com/1209590078', '', 2026, '{}', 15, false, true),
  ('2d-anime-animation-p1', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 1', '', 'https://vimeo.com/1209871360', '', 2026, '{}', 16, false, true),
  ('2d-anime-animation-p2', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 2', '', 'https://vimeo.com/1209873743', '', 2026, '{}', 17, false, true),
  ('2d-anime-animation-p3', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 3', '', 'https://vimeo.com/1209878429', '', 2026, '{}', 18, false, true),
  ('watch-animation-p1', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 1', '', 'https://vimeo.com/1210024583', '', 2026, '{}', 19, false, true),
  ('watch-animation-p2', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 2', '', 'https://vimeo.com/1209875240', '', 2026, '{}', 20, false, true),
  ('watch-animation-p3', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 3', '', 'https://vimeo.com/1210034271', '', 2026, '{}', 21, false, true),
  ('ryse-drink-3d-product-animation-p1', 'video-editing', 'ryse-drink-3d-product-animation', 'Ryse Drink 3d Product Animation', 'Ryse Drink 3d Product Animation — Project 1', '', 'https://vimeo.com/1209880931', '', 2026, '{}', 22, false, true),
  ('ryse-drink-3d-product-animation-p2', 'video-editing', 'ryse-drink-3d-product-animation', 'Ryse Drink 3d Product Animation', 'Ryse Drink 3d Product Animation — Project 2', '', 'https://vimeo.com/1210027183', '', 2026, '{}', 23, false, true),
  ('3d-perfume-animation-p1', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 1', '', 'https://vimeo.com/1210021198', '', 2026, '{}', 24, false, true),
  ('3d-perfume-animation-p2', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 2', '', 'https://vimeo.com/1210022540', '', 2026, '{}', 25, false, true),
  ('3d-perfume-animation-p3', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 3', '', 'https://vimeo.com/1210043587', '', 2026, '{}', 26, false, true),
  ('kids-learning-animation-p1', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 1', '', 'https://vimeo.com/1210028298', '', 2026, '{}', 27, false, true),
  ('kids-learning-animation-p2', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 2', '', 'https://vimeo.com/1210031405', '', 2026, '{}', 28, false, true),
  ('kids-learning-animation-p3', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 3', '', 'https://vimeo.com/1210036662', '', 2026, '{}', 29, false, true),
  ('3d-gadget-animation-p1', 'video-editing', '3d-gadget-animation', '3d Gadget Animation', '3d Gadget Animation — Project 1', '', 'https://vimeo.com/1210032939', '', 2026, '{}', 30, false, true),
  ('3d-gadget-animation-p2', 'video-editing', '3d-gadget-animation', '3d Gadget Animation', '3d Gadget Animation — Project 2', '', 'https://vimeo.com/1210045912', '', 2026, '{}', 31, false, true),
  ('3d-cartoon-animation-p1', '3d-animation', '3d-cartoon-animation', '3d Cartoon Animation', '3d Cartoon Animation — Project 1', '', 'https://vimeo.com/1210037919', '', 2026, '{}', 32, false, true),
  ('3d-cartoon-animation-p2', '3d-animation', '3d-cartoon-animation', '3d Cartoon Animation', '3d Cartoon Animation — Project 2', '', 'https://vimeo.com/1210036662', '', 2026, '{}', 33, false, true),
  ('vape-animation-p1', 'video-editing', 'vape-animation', 'Vape Animation', 'Vape Animation — Project 1', '', 'https://vimeo.com/1210039359', '', 2026, '{}', 34, false, true),
  ('vape-animation-p2', 'video-editing', 'vape-animation', 'Vape Animation', 'Vape Animation — Project 2', '', 'https://vimeo.com/1210041382', '', 2026, '{}', 35, false, true),
  ('3d-explainer-video-p1', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 1', '', 'https://vimeo.com/1210049156', '', 2026, '{}', 36, false, true),
  ('3d-explainer-video-p2', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 2', '', 'https://vimeo.com/1210050482', '', 2026, '{}', 37, false, true),
  ('3d-explainer-video-p3', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 3', '', 'https://vimeo.com/1210052577', '', 2026, '{}', 38, false, true),
  ('3d-explainer-video-p4', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 4', '', 'https://vimeo.com/1210053768', '', 2026, '{}', 39, false, true),
  ('3d-explainer-video-p5', '3d-animation', '3d-explainer-video', '3d Explainer Video', '3d Explainer Video — Project 5', '', 'https://vimeo.com/1210054201', '', 2026, '{}', 40, false, true),
  ('ronix-p1', 'branding', 'ronix', 'Ronix', 'Ronix — Project 1', '', 'https://vimeo.com/1210047470', '', 2026, '{}', 41, false, true),
  ('mintec-p1', 'branding', 'mintec', 'Mintec', 'Mintec — Project 1', '', 'https://youtu.be/y0tCd75JETE', '', 2026, '{}', 42, false, true),
  ('mintec-p2', 'branding', 'mintec', 'Mintec', 'Mintec — Project 2', '', 'https://youtu.be/DkVe89WP9y4', '', 2026, '{}', 43, false, true),
  ('integra-pw-p1', 'branding', 'integra-pw', 'Integra Pw', 'Integra Pw — Project 1', '', 'https://youtu.be/8OWfEeomZSQ', '', 2026, '{}', 44, false, true),
  ('integra-pw-p2', 'branding', 'integra-pw', 'Integra Pw', 'Integra Pw — Project 2', '', 'https://youtu.be/0SLmd1xJau4', '', 2026, '{}', 45, false, true),
  ('credex-p1', 'branding', 'credex', 'Credex', 'Credex — Project 1', '', 'https://youtu.be/jCvKcYOZN6Y', '', 2026, '{}', 46, false, true),
  ('phr-1-p1', 'branding', 'phr-1', 'Phr 1', 'Phr 1 — Project 1', '', 'https://youtu.be/2T6xaLcR7j0', '', 2026, '{}', 47, false, true),
  ('atx-p1', 'branding', 'atx', 'Atx', 'Atx — Project 1', '', 'https://youtu.be/dieHa2b-aCQ', '', 2026, '{}', 48, false, true),
  ('prov-gap-p1', 'branding', 'prov-gap', 'Prov Gap', 'Prov Gap — Project 1', '', 'https://vimeo.com/1210273972', '', 2026, '{}', 49, false, true),
  ('autoz-crave-p1', 'video-editing', 'autoz-crave', 'Autoz Crave', 'Autoz Crave — Project 1', '', 'https://youtu.be/Au_RJh88iSQ', '', 2026, '{}', 50, false, true),
  ('bag-suitcase-animation-p1', 'video-editing', 'bag-suitcase-animation', 'Bag Suitcase Animation', 'Bag Suitcase Animation — Project 1', '', 'https://youtu.be/cieiw04LGuc', '', 2026, '{}', 51, false, true),
  ('drop-band-animation-p1', 'video-editing', 'drop-band-animation', 'Drop Band Animation', 'Drop Band Animation — Project 1', '', 'https://youtu.be/dfLK-4XvxkQ', '', 2026, '{}', 52, false, true),
  ('drop-band-animation-p2', 'video-editing', 'drop-band-animation', 'Drop Band Animation', 'Drop Band Animation — Project 2', '', 'https://youtu.be/GIex1w7x0-c', '', 2026, '{}', 53, false, true),
  ('3d-medical-animation-p1', '3d-animation', '3d-medical-animation', '3d Medical Animation', '3d Medical Animation — Project 1', '', 'https://youtu.be/_49zfG03G1U', '', 2026, '{}', 54, false, true),
  ('3d-medical-animation-p2', '3d-animation', '3d-medical-animation', '3d Medical Animation', '3d Medical Animation — Project 2', '', 'https://youtu.be/yfGZMp-JKnY', '', 2026, '{}', 55, false, true),
  ('3d-bed-animation-p1', '3d-animation', '3d-bed-animation', '3d Bed Animation', '3d Bed Animation — Project 1', '', 'https://youtu.be/3QJaP9td0Uo', '', 2026, '{}', 56, false, true),
  ('3d-bed-animation-p2', '3d-animation', '3d-bed-animation', '3d Bed Animation', '3d Bed Animation — Project 2', '', 'https://vimeo.com/1210301766', '', 2026, '{}', 57, false, true),
  ('3d-anime-character-p1', '3d-animation', '3d-anime-character', '3d Anime Character', '3d Anime Character — Project 1', '', 'https://youtube.com/shorts/br2ODn6Y6oo', '', 2026, '{}', 58, false, true)
on conflict (project_key) do update set
  category_slug = excluded.category_slug,
  client_slug = excluded.client_slug,
  client_name = excluded.client_name,
  title = excluded.title,
  video_url = excluded.video_url,
  sort_order = excluded.sort_order,
  published = excluded.published;

