insert into public.portfolio_videos
  (project_key, category_slug, client_slug, client_name, title, description, video_url, thumbnail_url, year, tags, sort_order, featured, published)
values
  ('chibi-art-p1', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 1', '', 'https://youtube.com/shorts/cHhg9l3akjU', '', 2026, '{}', 0, false, true),
  ('chibi-art-p2', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 2', '', 'https://youtu.be/iZJPcVn6W9o', '', 2026, '{}', 1, false, true),
  ('chibi-art-p3', '2d-animation', 'chibi-art', 'Chibi Art', 'Chibi Art — Project 3', '', 'https://youtu.be/9p4tQexHeoc', '', 2026, '{}', 2, false, true),
  ('vtuber-animation-p1', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 1', '', 'https://vimeo.com/1209255164', '', 2026, '{}', 3, false, true),
  ('vtuber-animation-p2', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 2', '', 'https://vimeo.com/1209258090', '', 2026, '{}', 4, false, true),
  ('vtuber-animation-p3', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 3', '', 'https://youtu.be/O-BoHvEjl7k', '', 2026, '{}', 5, false, true),
  ('vtuber-animation-p4', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 4', '', 'https://vimeo.com/1209843856', '', 2026, '{}', 6, false, true),
  ('vtuber-animation-p5', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 5', '', 'https://youtu.be/e2Doy-zqTOk', '', 2026, '{}', 7, false, true),
  ('vtuber-animation-p6', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 6', '', 'https://vimeo.com/1209847191', '', 2026, '{}', 8, false, true),
  ('vtuber-animation-p7', '2d-animation', 'vtuber-animation', 'Vtuber Animation', 'Vtuber Animation — Project 7', '', 'https://youtu.be/qSA1wS9F9Zw', '', 2026, '{}', 9, false, true),
  ('live2d-animation-p1', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 1', '', 'https://youtu.be/4mRu2w4ajGY', '', 2026, '{}', 10, false, true),
  ('live2d-animation-p2', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 2', '', 'https://vimeo.com/1209580152', '', 2026, '{}', 11, false, true),
  ('live2d-animation-p3', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 3', '', 'https://youtu.be/Lz8O7KEBFdQ', '', 2026, '{}', 12, false, true),
  ('live2d-animation-p4', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 4', '', 'https://youtube.com/shorts/EyPeketx70A', '', 2026, '{}', 13, false, true),
  ('live2d-animation-p5', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 5', '', 'https://youtube.com/shorts/tYc1L2uSahI', '', 2026, '{}', 14, false, true),
  ('live2d-animation-p6', '2d-animation', 'live2d-animation', 'Live2d Animation', 'Live2d Animation — Project 6', '', 'https://vimeo.com/1209590078', '', 2026, '{}', 15, false, true),
  ('2d-anime-animation-p1', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 1', '', 'https://vimeo.com/1209871360', '', 2026, '{}', 16, false, true),
  ('2d-anime-animation-p2', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 2', '', 'https://vimeo.com/1209873743', '', 2026, '{}', 17, false, true),
  ('2d-anime-animation-p3', '2d-animation', '2d-anime-animation', '2d Anime Animation', '2d Anime Animation — Project 3', '', 'https://vimeo.com/1209878429', '', 2026, '{}', 18, false, true),
  ('watch-animation-p1', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 1', '', 'https://vimeo.com/1210024583', '', 2026, '{}', 19, false, true),
  ('watch-animation-p2', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 2', '', 'https://vimeo.com/1209875240', '', 2026, '{}', 20, false, true),
  ('watch-animation-p3', '3d-animation', 'watch-animation', 'Watch Animation', 'Watch Animation — Project 3', '', 'https://vimeo.com/1210034271', '', 2026, '{}', 21, false, true),
  ('ryse-drink-3d-product-animation-p1', 'video-editing', 'ryse-drink-3d-product-animation', 'Ryse Drink 3d Product Animation', 'Ryse Drink 3d Product Animation — Project 1', '', 'https://vimeo.com/1209880931', '', 2026, '{}', 22, false, true),
  ('ryse-drink-3d-product-animation-p2', 'video-editing', 'ryse-drink-3d-product-animation', 'Ryse Drink 3d Product Animation', 'Ryse Drink 3d Product Animation — Project 2', '', 'https://vimeo.com/1210027183', '', 2026, '{}', 23, false, true),
  ('3d-perfume-animation-p1', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 1', '', 'https://vimeo.com/1210021198', '', 2026, '{}', 24, false, true),
  ('3d-perfume-animation-p2', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 2', '', 'https://vimeo.com/1210022540', '', 2026, '{}', 25, false, true),
  ('3d-perfume-animation-p3', 'video-editing', '3d-perfume-animation', '3d Perfume Animation', '3d Perfume Animation — Project 3', '', 'https://vimeo.com/1210043587', '', 2026, '{}', 26, false, true),
  ('kids-learning-animation-p1', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 1', '', 'https://vimeo.com/1210028298', '', 2026, '{}', 27, false, true),
  ('kids-learning-animation-p2', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 2', '', 'https://vimeo.com/1210031405', '', 2026, '{}', 28, false, true),
  ('kids-learning-animation-p3', '3d-animation', 'kids-learning-animation', 'Kids Learning Animation', 'Kids Learning Animation — Project 3', '', 'https://vimeo.com/1210036662', '', 2026, '{}', 29, false, true)
on conflict (project_key) do update set
  category_slug = excluded.category_slug,
  client_slug = excluded.client_slug,
  client_name = excluded.client_name,
  title = excluded.title,
  video_url = excluded.video_url,
  sort_order = excluded.sort_order,
  published = excluded.published;