/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteReviewRouteImport } from './routes/write-review'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EuGdprRouteImport } from './routes/eu-gdpr'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WorksCategoryRouteImport } from './routes/works.$category'
import { Route as ServicesEntertainmentRouteImport } from './routes/services.entertainment'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as WorksCategoryIndexRouteImport } from './routes/works.$category.index'
import { Route as WorksCategoryClientRouteImport } from './routes/works.$category.$client'

const WriteReviewRoute = WriteReviewRouteImport.update({
  id: '/write-review',
  path: '/write-review',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EuGdprRoute = EuGdprRouteImport.update({
  id: '/eu-gdpr',
  path: '/eu-gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndustriesRoute,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WorksCategoryRoute = WorksCategoryRouteImport.update({
  id: '/works/$category',
  path: '/works/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesEntertainmentRoute = ServicesEntertainmentRouteImport.update({
  id: '/entertainment',
  path: '/entertainment',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const WorksCategoryIndexRoute = WorksCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorksCategoryRoute,
} as any)
const WorksCategoryClientRoute = WorksCategoryClientRouteImport.update({
  id: '/$client',
  path: '/$client',
  getParentRoute: () => WorksCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/eu-gdpr': typeof EuGdprRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/write-review': typeof WriteReviewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/entertainment': typeof ServicesEntertainmentRoute
  '/works/$category': typeof WorksCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/$category/$client': typeof WorksCategoryClientRoute
  '/works/$category/': typeof WorksCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/eu-gdpr': typeof EuGdprRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/write-review': typeof WriteReviewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/entertainment': typeof ServicesEntertainmentRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/services': typeof ServicesIndexRoute
  '/works/$category/$client': typeof WorksCategoryClientRoute
  '/works/$category': typeof WorksCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/eu-gdpr': typeof EuGdprRoute
  '/faq': typeof FaqRoute
  '/imprint': typeof ImprintRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/write-review': typeof WriteReviewRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/entertainment': typeof ServicesEntertainmentRoute
  '/works/$category': typeof WorksCategoryRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/works/$category/$client': typeof WorksCategoryClientRoute
  '/works/$category/': typeof WorksCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/eu-gdpr'
    | '/faq'
    | '/imprint'
    | '/industries'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/write-review'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/translations'
    | '/admin/videos'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/services/entertainment'
    | '/works/$category'
    | '/admin/'
    | '/blog/'
    | '/case-studies/'
    | '/industries/'
    | '/services/'
    | '/works/$category/$client'
    | '/works/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/eu-gdpr'
    | '/faq'
    | '/imprint'
    | '/portfolio'
    | '/privacy'
    | '/write-review'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/translations'
    | '/admin/videos'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/services/entertainment'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/industries'
    | '/services'
    | '/works/$category/$client'
    | '/works/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/case-studies'
    | '/contact'
    | '/eu-gdpr'
    | '/faq'
    | '/imprint'
    | '/industries'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/write-review'
    | '/admin/admins'
    | '/admin/blogs'
    | '/admin/categories'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/reviews'
    | '/admin/translations'
    | '/admin/videos'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/services/entertainment'
    | '/works/$category'
    | '/admin/'
    | '/blog/'
    | '/case-studies/'
    | '/industries/'
    | '/services/'
    | '/works/$category/$client'
    | '/works/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  EuGdprRoute: typeof EuGdprRoute
  FaqRoute: typeof FaqRoute
  ImprintRoute: typeof ImprintRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  WriteReviewRoute: typeof WriteReviewRoute
  WorksCategoryRoute: typeof WorksCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write-review': {
      id: '/write-review'
      path: '/write-review'
      fullPath: '/write-review'
      preLoaderRoute: typeof WriteReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu-gdpr': {
      id: '/eu-gdpr'
      path: '/eu-gdpr'
      fullPath: '/eu-gdpr'
      preLoaderRoute: typeof EuGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/industries/': {
      id: '/industries/'
      path: '/'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/works/$category': {
      id: '/works/$category'
      path: '/works/$category'
      fullPath: '/works/$category'
      preLoaderRoute: typeof WorksCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/entertainment': {
      id: '/services/entertainment'
      path: '/entertainment'
      fullPath: '/services/entertainment'
      preLoaderRoute: typeof ServicesEntertainmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/works/$category/': {
      id: '/works/$category/'
      path: '/'
      fullPath: '/works/$category/'
      preLoaderRoute: typeof WorksCategoryIndexRouteImport
      parentRoute: typeof WorksCategoryRoute
    }
    '/works/$category/$client': {
      id: '/works/$category/$client'
      path: '/$client'
      fullPath: '/works/$category/$client'
      preLoaderRoute: typeof WorksCategoryClientRouteImport
      parentRoute: typeof WorksCategoryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesEntertainmentRoute: typeof ServicesEntertainmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesEntertainmentRoute: ServicesEntertainmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WorksCategoryRouteChildren {
  WorksCategoryClientRoute: typeof WorksCategoryClientRoute
  WorksCategoryIndexRoute: typeof WorksCategoryIndexRoute
}

const WorksCategoryRouteChildren: WorksCategoryRouteChildren = {
  WorksCategoryClientRoute: WorksCategoryClientRoute,
  WorksCategoryIndexRoute: WorksCategoryIndexRoute,
}

const WorksCategoryRouteWithChildren = WorksCategoryRoute._addFileChildren(
  WorksCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  EuGdprRoute: EuGdprRoute,
  FaqRoute: FaqRoute,
  ImprintRoute: ImprintRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  WriteReviewRoute: WriteReviewRoute,
  WorksCategoryRoute: WorksCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
